name: Docker Image CI

on:
  push:
    branches: [master]
  schedule:
    - cron: "0 0 1 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag mavnt/alpine-net-tools:latest && echo ${{ secrets.DOCKER_TOKEN }} | docker login -u=mavnt --password-stdin; docker push mavnt/alpine-net-tools:latest
